# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e28c5c04c85b3157487c7f2ce006e711c236527ba45f062aabe90dbe1984ab1d8baffede33eeb7ac70ae22e930cd8c10ba1b9afca1570d68cdbd78de05bf05e7

test:
  secret_key_base: e7916ab1efbb76fb6e4815afd2d46072ae102f9fbeb9ec655a5ffc1362b528772963d77d39ef884b300d0dac4579486ee4af46d940349eb87439106fa80fea49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
